[project]
name = "action"
version = "1.1.0"
description = "Automated Camera Trapping Identification and Organization Network (ACTION)"
repository = "https://github.com/humphrem/action"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE"
authors = [ "Morgan Humphrey", "David Humphrey"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
download = "python scripts/download.py"
install-requirements = "pip install -r requirements.txt"
setup = {depends_on=["install-requirements", "download"]}
lint = "ruff check ."

[dependencies]
python = ">=3.12.5,<3.13"
ffmpeg = ">=6.1.1,<7.1"
pip = "23.2.1.*"
git = "2.42.0.*"
numpy = ">=2.1.1,<2.2"
ruff = ">=0.6.4,<0.7"
requests = ">=2.32.3,<2.33"
